### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by skafandri** [tokenpay/tokenpay#18]
When running `tokenpay -testnet` the application starts then nothing happens. No peers are discovered, no blockchain is downloaded.

**Comment by theodor96** [comment]
Should be fixed by this: https://github.com/tokenpay/tokenpay/pull/19

**Comment by markair77** [comment]
Great work, I just wanted to hear your thoughts on this, and because of POS and UTXO, is TokenPay safe from this exploit, and proper security measures implemented? It was interesting to see the list of coins that were checked... Anyway keep up the good work and I look forward to to testing eFin beta.
-----
https://medium.com/@dsl_uiuc/fake-stake-attacks-on-chain-based-proof-of-stake-cryptocurrencies-b8b05723f806

**Comment by skafandri** [comment]
@theodor96 check the article from @markair77, interesting reading

**Comment by theodor96** [comment]
> ## Great work, I just wanted to hear your thoughts on this, and because of POS and UTXO, is TokenPay safe from this exploit, and proper security measures implemented? It was interesting to see the list of coins that were checked... Anyway keep up the good work and I look forward to to testing eFin beta.
> https://medium.com/@dsl_uiuc/fake-stake-attacks-on-chain-based-proof-of-stake-cryptocurrencies-b8b05723f806

Thank you for bringing this to our attention. Will definitely investigate.
